# Generated by Django 5.1.4 on 2026-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Autor de IA',
                'verbose_name_plural': 'Autores de IA',
            },
        ),
        migrations.CreateModel(
            name='NeuralNetworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('use_case', models.TextField()),
                ('icon', models.CharField(default='network', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Red Neuronal',
                'verbose_name_plural': 'Tipos de Redes Neuronales',
            },
        ),
    ]
